# Generated by Django 5.0.3 on 2024-03-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='willTutor',
            field=models.BooleanField(default=False),
        ),
    ]
