# Generated by Django 5.0.3 on 2024-03-28 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_courses_tutoringform_tutoringsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringform',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tutoringsession',
            name='Tutroing_Date',
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='Description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tutoringsession',
            name='Tutrorng_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
