# Generated by Django 5.0.3 on 2024-03-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_tutoringform_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseNumber', models.CharField(max_length=50)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AlterField(
            model_name='tutoringform',
            name='courses',
            field=models.ManyToManyField(to='home.course'),
        ),
    ]
