# Generated by Django 5.0.4 on 2024-04-08 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_tutrorng_date_tutoringsession_tutoring_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringform',
            name='Tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TutoringForm', to=settings.AUTH_USER_MODEL),
        ),
    ]
