# Generated by Django 5.0.4 on 2024-04-12 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_tutoringform_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='TutoringForm',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='home.tutoringform'),
        ),
        migrations.AlterField(
            model_name='tutoringform',
            name='Tutor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='TutorForm', to=settings.AUTH_USER_MODEL),
        ),
    ]
