# Generated by Django 5.0.3 on 2024-05-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_chat_user1_remove_chat_user2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mon', models.BooleanField(default=False)),
                ('Tue', models.BooleanField(default=False)),
                ('Wed', models.BooleanField(default=False)),
                ('Thu', models.BooleanField(default=False)),
                ('Fri', models.BooleanField(default=False)),
                ('Sat', models.BooleanField(default=False)),
                ('Sun', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='days',
            field=models.ManyToManyField(to='home.days'),
        ),
    ]
