# Generated by Django 5.0.4 on 2024-05-06 08:59

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_chat_user1_remove_chat_user2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='Tutoring_Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tutoringsession',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
