# Generated by Django 5.0.3 on 2024-05-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_days_tutoringform_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringform',
            name='days',
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='Fri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='Mon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='Sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='Sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='Thu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='Tue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='Wed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Days',
        ),
    ]
