# Generated by Django 5.0.4 on 2024-05-06 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_tutoringsession_tutoring_date_and_more'),
        ('home', '0012_remove_tutoringform_days_tutoringform_fri_and_more'),
    ]

    operations = [
    ]
