# Generated by Django 5.0.4 on 2024-05-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20240506_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringform',
            name='Messaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='OnCampus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutoringform',
            name='Zoom',
            field=models.BooleanField(default=False),
        ),
    ]
